### PR TITLE
#306 multiple users as project lead

### PR DESCRIPTION
**Pull request by jinhyunh**
changed prisma schema and the types in the src file for a WbsElement to take in more than one project lead. Changed all calls of the fullNamePipe of the project lead to be a list pipe of the array of project leads that does the fullNamePipe of each. corrected inputs of tests to input an array of project leads.

### CODE REVIEW

**Comment by jinhyunh** [comment]
the pipe.tsx does not have to be changed for this issue and somehow it got changed

**Review by jamescd18 — CHANGES_REQUESTED** [review]
This is fantastic! I love seeing how you've thoroughly scrubbed through all the places in the code to make the adjustment, as well as going through each part of the application that this change impacts.

There's still a few things missing though:
- [x] Updating the prisma database seed objects
- [x] Updating the prisma database seed script
- [ ] Adding screenshots of what it would look like to have multiple project leads in the various parts of the app where the change impacts

**Comment by jinhyunh** [comment]
image

**Comment by jinhyunh** [comment]
image

**Review by jamescd18 — DISMISSED** [review]
This looks great! Nicely done with catching all the pieces that need to be updated. There's still some merge conflicts that you'll need to resolve and then I think you'll need to re-request review.

**Review by jamescd18 — APPROVED** [review]
Amazingly thorough! I love it!

**Pull request merged**
