### PR TITLE
#530 add scripts to check and enforce prettier

### PR DESCRIPTION
**Pull request by jpwaves**
## Changes

Added 2 scripts to `package.json`, one for checking prettier on files and one for enforcing prettier formatting.

## Notes

I don't know which files/folders to have prettier to ignore. I'll need to add that into a prettier config file before finishing this pull request.

## Test Cases

None

## Screenshots (if applicable)

None

## To Do

- [x] Create prettier config file for what files to ignore
- [x] Move prettier config options from `package.json` into a separate prettier config file

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/main/docs/ContributorGuide.md) and reach out to your squad if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors
- [x] No newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (if applicable)
- [x] Remove any not-applicable sections
- [x] Assign the PR to yourself
- [x] PR is linked to the ticket
- [x] No `package-lock.json` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack

Closes # (issue #)

### CODE REVIEW

**Review by jamescd18 — COMMENTED** [review]
Lol that's way simpler than expected. Looks like a good start tho. 

Because we don't have any prettier ignore patterns, I'm pretty sure prettier is applied to all files in the repo. The main idea here tho is that it is applied to ts, tsx, js, json, css, md, and html. Are there any issues with applying it to all files? Does it cause sweeping changes if you do? (Which would indicate we're not currently running it on all files)

Also, I don't care / don't know whether it's in this ticket or another ticket, this PR or another PR, but I want to see if we can get this script to be run as a GitHub Action check for all PRs, just the way we do with linting. This would dramatically improve our ability to easily enforce prettier formatting.

**Review by jamescd18 — CHANGES_REQUESTED** [review]
Oops, yes, `src/utils/lib` is definitely generated and should be ignored for prettier. Definitely any generated files should be ignored. What other files are showing need changes? Requesting changes for these include/exclude files stuff. 

I'm not too keen on a pre-commit hook unless you think it's the proper way to do this. I have second-hand bad experience with pre-commit hooks from first co-op which is why I was suggesting trying to get it to run as a check and show up in GitHub in-line with the files changed tab, just the way lint errors are shown. What do you think?

**Comment by jpwaves** [comment]
> Oops, yes, `src/utils/lib` is definitely generated and should be ignored for prettier. Definitely any generated files should be ignored. What other files are showing need changes? Requesting changes for these include/exclude files stuff.
> 
> I'm not too keen on a pre-commit hook unless you think it's the proper way to do this. I have second-hand bad experience with pre-commit hooks from first co-op which is why I was suggesting trying to get it to run as a check and show up in GitHub in-line with the files changed tab, just the way lint errors are shown. What do you think?

The pre-commit hook I was thinking of was just running the prettier enforce script before the commit to make sure everything is prettified so devs don't need to worry about it, which is what we do at my co-op. I'm not sure what issues you have with pre-commit hooks, but from my experience, they're a nice convenience to have. What exactly went wrong with the pre-commit hooks at your co-op?

**Comment by jamescd18** [comment]
Oh lol if you do it co-op then don’t let me stop you. Go right ahead and lets do it as a pre-commit hook. My bad experience is just the other co-op struggling to ever get a pre-commit hook going for sonarlint scans. Very stupid bad experience, not at all warranting us avoiding it.

**Comment by jpwaves** [comment]
Here's a screenshot of all the files triggering warnings by prettier:
prettier-warnings

**Comment by jpwaves** [comment]
> Oh lol if you do it co-op then don’t let me stop you. Go right ahead and lets do it as a pre-commit hook. My bad experience is just the other co-op struggling to ever get a pre-commit hook going for sonarlint scans. Very stupid bad experience, not at all warranting us avoiding it.

We'll make creating the pre-commit hook a separate ticket then, in case any of the other devs want to try their hands at this.

**Comment by acd124** [comment]
Should we also be checking css files as well? Might be worth including too. I'm more on the fence about json, but it might be considered.

**Comment by jpwaves** [comment]
> Should we also be checking css files as well? Might be worth including too. I'm more on the fence about json, but it might be considered.

Yeah, we should probably check CSS files too. I can convert the json file to  a `.js` file instead - `.json` just happened to be the quickest and easiest way to move the configs.

**Comment by jpwaves** [comment]
New screenshot of tagged files:
prettierlogs1

**Comment by jamescd18** [comment]
Does `.test.tsx` need to be called out separately? Does that mean we also need to call out all our other fun extensions like `.hooks.tsx` or `.api.ts`

**Comment by jpwaves** [comment]
> Does `.test.tsx` need to be called out separately? Does that mean we also need to call out all our other fun extensions like `.hooks.tsx` or `.api.ts`

tested, guess not

**Review by jamescd18 — APPROVED** [review]
LGTM!

**Pull request merged**
