### PR TITLE
#477 standard date format v2

### PR DESCRIPTION
**Pull request by oneal55**
## Changes
Even though the datePipe was already existent, it hadn't been applied everywhere, so it was applied wherever it was missing.
## Notes
No other notes
## Test Cases
Updated all tests regarded dates to include the new date format

## Screenshots (if applicable)
_Any relevant screenshots go here_
image
image
image
image

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://github.com/Northeastern-Electric-Racing/PM-Dashboard-v2/blob/main/docs/ContributorGuide.md) and reach out to your squad if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors
- [x] No newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (if applicable)
- [x] Remove any not-applicable sections
- [x] Assign the PR to yourself
- [x] PR is linked to the ticket
- [x] No `package-lock.json` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack

Closes # (#477)

### CODE REVIEW

**Review by jamescd18 — APPROVED** [review]
Code changes look to be spot on! Awesome job! The one thing that is definitely something to avoid is force pushing. You shouldn't need to. Also, that one commit message where it's '#' instead of just #. Your tech lead should review first, then I'll review and merge

**Review by joshiarnav — APPROVED** [review]
Looks good to me too!

**Review by jamescd18 — CHANGES_REQUESTED** [review]
merge conflicts

**Review by jamescd18 — APPROVED** [review]
Awesome job! There's a lot here but it makes sense and it looks great to standardize all those dates! Thank you so much!

**Comment by jamescd18** [comment]
Closes #477

**Pull request merged**
