### PR TITLE
Populates Implemented Changes Section

### PR DESCRIPTION
**Pull request by RChandler234**
I've added the implemented changes list component to solve this issue. The implemented changes section is now populated and I believe the links work properly, I'm not sure if where I added the implemented changes list component is in the wrong spot, and I also need to add testing for it, but I wasn't sure how to do that. I'm working on implementing the final part of the ticket, the tooltip rn.

### CODE REVIEW

**Comment by RChandler234** [comment]
image

**Review by jamescd18 — COMMENTED** [review]
Love this! Great first step on the implementation and great usage of our helper components.

**Comment by RChandler234** [comment]
image
image

**Review by jamescd18 — CHANGES_REQUESTED** [review]
I'd love it if we could have the target for the tool tip be the whole bullet instead of just the link, and then also display the tool tip to the right so it doesn't cover up anything. Other than that it looks great!!

**Comment by RChandler234** [comment]
image
image
The target is now the text instead of the link-I couldn't get it to target the whole thing-and the tooltip displays to the right of the text.

**Review by jamescd18 — APPROVED** [review]
LGTM, love it! Really really love the tool tip!!

**Pull request merged**
